[[redirects]]
  from = "https://aitoolshubpro.me/*"
  to = "https://www.aitoolshubpro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://aitoolshubpro.com/*"
  to = "https://www.aitoolshubpro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.aitoolshubpro.com/*"
  to = "https://www.aitoolshubpro.me/:splat"
  status = 301
  force = true
