[[redirects]]
  from = "https://www.aitoolshubpro.me/*"
  to = "https://aitoolshubpro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://aitoolshubpro.com/*"
  to = "https://aitoolshubpro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.aitoolshubpro.com/*"
  to = "https://aitoolshubpro.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy.html"
  status = 301
  force = true
