name = "aitools"
compatibility_date = "2026-04-18"
main = "worker.js"
workers_dev = true
keep_vars = true

routes = [
	{ pattern = "aitoolshubpro.me/*", zone_name = "aitoolshubpro.me" },
	{ pattern = "www.aitoolshubpro.me/*", zone_name = "aitoolshubpro.me" }
]

[assets]
directory = "dist"
binding = "ASSETS"
run_worker_first = ["/admin", "/admin/*"]
